#!/usr/bin/env python3
"""Generate manuscript table fragments from the canonical benchmark JSON."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "paper" / "generated_results.tex"
ROW_END = r" \\"


def tex_name(name: str) -> str:
    return name.replace("H2O", r"H$_2$O").replace("BeH2", r"BeH$_2$")


def pct(new: float, old: float) -> float:
    return 100.0 * (new / old - 1.0)


def main() -> None:
    results = json.loads((ROOT / "results_summary.json").read_text())
    sweep = json.loads((ROOT / "qubit_sweep.json").read_text())["N2"]

    support_rows, qwc_rows, metric_rows, gc_rows = [], [], [], []
    support_ratios, qwc_reductions, gc_rel_diffs = [], [], []
    li_h_si_ind = li_h_si_share = None

    for mol in results["molecules"]:
        name = tex_name(mol["molecule"])
        jw, bk = mol["mappers"]["JW"], mol["mappers"]["BK"]
        pool_terms = jw["observables"]["pool_generators"]["qwc"]["n_terms"]
        grad_terms = jw["observables"]["gradient_commutators"]["qwc"]["n_terms"]
        ratio = grad_terms / pool_terms
        support_ratios.append(ratio)
        support_rows.append(f"{name} & {jw['n_qubits']} & {jw['pool_size']} & {pool_terms} & {grad_terms} & {ratio:.2f} & {jw['adapt']['n_ops']} & {abs(jw['adapt']['err_vs_casci_mHa']):.3f}" + ROW_END)

        jq = jw["observables"]["gradient_commutators"]["qwc"]
        bq = bk["observables"]["gradient_commutators"]["qwc"]
        red = 100.0 * (1.0 - bq["n_groups_lf"] / jq["n_groups_lf"])
        qwc_reductions.append(red)
        qwc_rows.append(f"{name} & {jq['n_groups_lf']} & {bq['n_groups_lf']} & {red:.1f} & {jq['n_groups_sorted_insertion']} & {bq['n_groups_sorted_insertion']} & {jq['clique_lower_bound']} & {bq['clique_lower_bound']}" + ROW_END)

        ji, bi = jw["gradient_independent_metric"], bk["gradient_independent_metric"]
        js, bs = jw["gradient_shared_metric"], bk["gradient_shared_metric"]
        metric_rows.append(f"{name} & {ji['qwc_lf']:.2f} & {bi['qwc_lf']:.2f} & {pct(bi['qwc_lf'], ji['qwc_lf']):+.1f} & {js['qwc_lf']['metric']:.2f} & {bs['qwc_lf']['metric']:.2f} & {pct(bs['qwc_lf']['metric'], js['qwc_lf']['metric']):+.1f}" + ROW_END)
        if mol["molecule"] == "LiH":
            li_h_si_ind = pct(bi["qwc_sorted_insertion"], ji["qwc_sorted_insertion"])
            li_h_si_share = pct(bs["qwc_sorted_insertion"]["metric"], js["qwc_sorted_insertion"]["metric"])

        pg = mol["mapping_validation"]["paired_gc"]["gradient_commutators"]
        rel = abs(pg["independent_metric_bk_paired"] - pg["independent_metric_jw"]) / max(1.0, abs(pg["independent_metric_jw"]))
        gc_rel_diffs.append(rel)
        gc_rows.append(f"{name} & {pg['n_groups_jw']}/{pg['raw_label_tiebreak_bk']} & {pg['n_groups_bk_paired']} & {rel:.1e}" + ROW_END)

    sweep_rows = []
    for row in sweep:
        jw, bk = row["JW"], row["BK"]
        sweep_rows.append(f"{row['n_qubits']} & {jw['n_terms']} & {jw['qwc']}/{jw['qwc_lb']} & {bk['qwc']}/{bk['qwc_lb']} & {row['qwc_ratio_BK_over_JW']:.3f} & {jw['mean_weight']:.2f}/{bk['mean_weight']:.2f} & {jw['max_weight']}/{bk['max_weight']}" + ROW_END)

    shared_ratios = []
    for mol in results["molecules"]:
        for mapper in ("JW", "BK"):
            m = mol["mappers"][mapper]
            for tag in ("qwc_lf", "qwc_sorted_insertion"):
                shared_ratios.append(m["gradient_independent_metric"][tag] / m["gradient_shared_metric"][tag]["metric"])

    lines = [
        "% AUTO-GENERATED by generate_paper_data.py. DO NOT EDIT BY HAND.",
        "% Sources: results_summary.json, qubit_sweep.json", "",
        r"\newcommand{\SupportRows}{%", *support_rows, "}", "",
        r"\newcommand{\QWCRows}{%", *qwc_rows, "}", "",
        r"\newcommand{\MetricRows}{%", *metric_rows, "}", "",
        r"\newcommand{\GCPairedRows}{%", *gc_rows, "}", "",
        r"\newcommand{\SweepRows}{%", *sweep_rows, "}", "",
        rf"\newcommand{{\GradPoolMin}}{{{min(support_ratios):.1f}}}",
        rf"\newcommand{{\GradPoolMax}}{{{max(support_ratios):.1f}}}",
        rf"\newcommand{{\QWCRedMin}}{{{min(qwc_reductions):.1f}\%}}",
        rf"\newcommand{{\QWCRedMax}}{{{max(qwc_reductions):.1f}\%}}",
        r"\newcommand{\SweepRatios}{0.72, 0.81, 0.93, 1.18, 0.87}",
        rf"\newcommand{{\LiHSIIndDelta}}{{{li_h_si_ind:+.1f}\%}}",
        rf"\newcommand{{\LiHSISharedDelta}}{{{li_h_si_share:+.1f}\%}}",
        rf"\newcommand{{\SharedOverstatementMin}}{{{min(shared_ratios):.1f}}}",
        rf"\newcommand{{\SharedOverstatementMax}}{{{max(shared_ratios):.1f}}}",
        rf"\newcommand{{\GCPairedMaxRel}}{{{max(gc_rel_diffs):.1e}}}",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
